### ISSUE TITLE
Broken Villagers

### ISSUE THREAD

**Issue by Jacqueb-1337** [Arthurmeade12/robojoe-smp-scripts#1]
Engineer Gaming says Villagers do not behave properly.

1. They get stuck on beds and can't move permanently until the bed is broken.
2. Iron golem spawn rate in the presence of villagers is exponentially smaller than vanilla (likely the anti-lag features in our version of paper is preventing them from `gossiping`)
3. They don't breed like they are supposed to, and sometimes won't breed at all. Not much info on this yet, but the main issue is that even after being given the `inLove` tag by giving 2 villagers near each other food, the villagers can sometimes take over 45 minutes to breed (even with heart particles appearing above them).  
4. When enclosing a villager in a room (even one with no entry points or any way for other villagers to pathfind to the area), a *random villager nearby* (sometimes being outside if the aforementioned closed room) will occupy a workstation placed by the player, making villager trading halls very hard to create.

**Comment by Arthurmeade12** [comment]
Response:

I will look into 1-3. #4 is vanilla behavior.

Also, so you have personal experience with this? Or have you just gathered up complaints from around the server (which is fine by the way)

**Comment by Jacqueb-1337** [comment]
> #4 is vanilla behavior.

Engineer said the same thing, but I did a test on a vanilla singleplayer world and could not reproduce the same thing on the server. 

Also I have had personal experience with some things listed but I have also gathered complaints of the rest.

**Comment by Arthurmeade12** [comment]
> Iron golem spawn rate in the presence of villagers is exponentially smaller than vanilla

Isn't there supposed to be one golem per village? I don't see how spawn rates for golems could be lower.

**Comment by Jacqueb-1337** [comment]
> Isn't there supposed to be one golem per village? I don't see how spawn rates for golems could be lower.

No, there's 1 Golem per 10 villagers, and they need a 16x6x16 area to spawn. The problem is, Iron Golem farms are broken at the moment because golem spawning timing is wrong. Under normal circumstances, golems have a 1 in 7,000 chance of spawning every tick, which comes out to about one golem spawn every 6 mins *if none are present*. Presently, one golem spawn every 20 to 30 mins per my own experience. I'm not sure, but it may just be that Villagers are forced into an inactive state for large amounts of time (since players don't usually sit right by their iron farms) and this causes the gossip tag to not change.

**Comment by Arthurmeade12** [comment]
This has been resolved by an internal conversation in discord.
